spring:
  application:
    name: MEMBER-SERVICE
  config:
    import:
      optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 9876
    username: guest
    password: guest
eureka:
  instance:
    client:
      serverUrl:
        defaultZone=http://localhost:8761/eureka/
server:
  port: 8082
