spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name:
      DEPARTMENT-SERVICE
  activemq:
    broker-url:
  rabbitmq:
    host: localhost
    port: 9876
    username: guest
    password: guest
eureka:
  instance:
    client:
      serverUrl:
        defaultZone=http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include=*:
